{% set version = '2.0.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-greg
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/Greg_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/Greg/Greg_{{ version }}.tar.gz
  sha256: 8cd4823b233f5c0e419314cd84e1cfb2a2b672a11c2efca4505eadc32dbdcbb0

build:
  merge_build_host: True           # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'                    # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-epi
    - r-gmisc >=1.0.3
    - r-hmisc
    - r-broom
    - r-dplyr
    - r-forestplot
    - r-glue
    - r-htmltable >=2.0.0
    - r-knitr
    - r-nlme
    - r-purrr
    - r-rlang
    - r-rms
    - r-sandwich
    - r-stringr
    - r-tibble
    - r-tidyr
    - r-tidyselect
  run:
    - r-base
    - r-epi
    - r-gmisc >=1.0.3
    - r-hmisc
    - r-broom
    - r-dplyr
    - r-forestplot
    - r-glue
    - r-htmltable >=2.0.0
    - r-knitr
    - r-nlme
    - r-purrr
    - r-rlang
    - r-rms
    - r-sandwich
    - r-stringr
    - r-tibble
    - r-tidyr
    - r-tidyselect

test:
  commands:
    - $R -e "library('Greg')"           # [not win]
    - "\"%R%\" -e \"library('Greg')\""  # [win]

about:
  home: http://gforge.se
  license: GPL-3.0-or-later
  summary: Methods for manipulating regression models and for describing these in a style adapted
    for medical journals. Contains functions for generating an HTML table with crude
    and adjusted estimates, plotting hazard ratio, plotting model estimates and confidence
    intervals using forest plots, extending this to comparing multiple models in a single
    forest plots. In addition to the descriptive methods, there are functions for the
    robust covariance matrix provided by the 'sandwich' package, a function for adding
    non-linearities to a model, and a wrapper around the 'Epi' package's Lexis() functions
    for time-splitting a dataset when modeling non-proportional hazards in Cox regressions.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - leej3

# Package: Greg
# Version: 2.0.1
# Title: Regression Helper Functions
# Maintainer: Max Gordon <max@gforge.se>
# Authors@R: c(person("Max", "Gordon", email = "max@gforge.se", role = c("aut", "cre")), person("Reinhard", "Seifert", role = "aut", comment = "Author of original plotHR"))
# Description: Methods for manipulating regression models and for describing these in a style adapted for medical journals. Contains functions for generating an HTML table with crude and adjusted estimates, plotting hazard ratio, plotting model estimates and confidence intervals using forest plots, extending this to comparing multiple models in a single forest plots. In addition to the descriptive methods, there are functions for the robust covariance matrix provided by the 'sandwich' package, a function for adding non-linearities to a model, and a wrapper around the 'Epi' package's Lexis() functions for time-splitting a dataset when modeling non-proportional hazards in Cox regressions.
# License: GPL (>= 3)
# URL: http://gforge.se
# BugReports: https://github.com/gforge/Greg/issues
# Biarch: yes
# Encoding: UTF-8
# Imports: broom, Epi, dplyr, glue, graphics, grDevices, htmlTable (>= 2.0.0), Hmisc, knitr, methods, nlme, purrr, rlang, rms, sandwich, stats, stringr, tibble, tidyr, tidyselect, utils
# Depends: Gmisc (>= 1.0.3), forestplot, R (>= 4.1.0)
# Suggests: boot, testthat, cmprsk, survival, ggplot2, parallel, rmarkdown, rmeta, tidyverse
# VignetteBuilder: knitr
# RoxygenNote: 7.2.1
# NeedsCompilation: no
# Packaged: 2022-11-15 20:01:01 UTC; max
# Author: Max Gordon [aut, cre], Reinhard Seifert [aut] (Author of original plotHR)
# Repository: CRAN
# Date/Publication: 2022-11-16 09:50:02 UTC
